# Generated by Django 4.2.4 on 2023-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_emergency_latitude_alter_emergency_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
